# Generated by Django 2.0.6 on 2018-06-22 05:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('line_1_number_bilding', models.CharField(max_length=255)),
                ('line_2_number_street', models.CharField(max_length=255)),
                ('line_3_area_locality', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip_postcode', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('iso_country_code', models.IntegerField()),
                ('other_address_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to', models.DateField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_customers.Addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Payment_Methods',
            fields=[
                ('customer_payment_method_id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=150)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('other_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 20 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('customer_email', models.CharField(blank=True, max_length=50, unique=True)),
                ('other_customer_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Address_type',
            fields=[
                ('address_type_code', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('address_type_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Pyament_Methods',
            fields=[
                ('payment_method_description', models.CharField(choices=[('AM', 'AmEx'), ('MC', 'MasterCard'), ('CSH', 'Cash')], max_length=255)),
                ('payment_method_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='customer_payment_methods',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_customers.Customers'),
        ),
        migrations.AddField(
            model_name='customer_payment_methods',
            name='payment_method_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_customers.Ref_Pyament_Methods'),
        ),
        migrations.AddField(
            model_name='customer_addresses',
            name='address_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_customers.Ref_Address_type'),
        ),
        migrations.AddField(
            model_name='customer_addresses',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_customers.Customers'),
        ),
        migrations.AddField(
            model_name='customer_addresses',
            name='date_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_customers.Customer_Payment_Methods'),
        ),
    ]
